### ISSUE TITLE
执行DVClassification分类任务，出现 CUDA kernel failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by dhliubj** [dvlab-research/DeepVision3D#1]
你好，

我在执行DVClassification分类任务，出现 `CUDA kernel failed : no kernel image is available for execution on the device`。

我已经完成了 [Installing DeepVision3D ToolBox](https://github.com/dvlab-research/DeepVision3D/blob/master/docs/Installation.md)所有安装步骤。

我已经重复了3次安装，在执行 `python train_classification.py --config config/eqpointnet2.yaml --process_data` 的时候，均出现了 `CUDA kernel failed : no kernel image is available for execution on the device` 问题。

我使用的显卡是 3070
安装的torch版本是 1.10.1
使用的cuda版本是 11.3

![Screenshot from 2022-05-20 14-21-58.png](https://s2.loli.net/2022/05/20/paOVmbABcqDeUR9.png)

期待可以得到解答，谢谢！

**Comment by tomztyang** [comment]
Could you please share your installation instruction here?

Thanks.
Zetong

**Comment by dhliubj** [comment]
> Could you please share your installation instruction here?
> 
> Thanks. Zetong

Here are the steps of my installation ([Installing DeepVision3D ToolBox](https://github.com/dvlab-research/DeepVision3D/blob/master/docs/Installation.md) was referenced).

------

**(1) Clone this repository.**

```shell
git clone https://github.com/dvlab-research/DeepVision3D
```
**(2) Build anaconda Environment.**

```shell
conda create -n dv3d python=3.8 -y
conda activate dv3d
```
**(3) Install PyTorch and torchvision** following the [official instructions](https://pytorch.org/).

`E.g. 2` To install PyTorch 1.10.1 with a CUDA version of 11.3:
```shell
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
```

**(4) Install requirements.**

```shell
cd /path/to/DeepVision3D
pip install -r requirements.txt
```

**(5) Build [MMCV](https://mmcv.readthedocs.io/en/latest/).**

`E.g. 2` To install mmcv on PyTorch 1.10.0 with CUDA 11.1:

```shell
pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
```
More information can be found at [here](https://mmcv.readthedocs.io/en/latest/get_started/installation.html)

**(6) Build [MMDetection3D](https://github.com/open-mmlab/mmdetection3d)**

* Install dependencies:
    ```shell
    pip install mmdet==2.22.0 
    pip install mmsegmentation==0.22.0
    ```
* Build MMDetection3D.
    ```shell
    cd /path/to/DeepVision3D/MMDetection3D
    python setup.py develop
    ```

**(7) Build [SparseConv](https://github.com/traveller59/spconv) library and [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) (We use `spconv v1.2.1`).**

* Clone spconv v1.2.1:
    ```sh
    git clone -b v1.2.1 https://github.com/traveller59/spconv --recursive
    ```
* Install cmake & libboost:
    ```sh
    conda install -c statiskit libboost-dev && conda install -c anaconda cmake
    ```
* Build spconv library:
    ```sh
    cd spconv && python setup.py bdist_wheel
    ```
  
* Install spconv:
  ```sh
  cd ./dist && pip install spconv-1.2.1-cp38-cp38-linux_x86_64.whl
  ```
* Install OpenPCDet:
  ```sh
  cd /path/to/DeepVision3D/OpenPCDet && python setup.py develop
  ```

(8) Build EQNet.
```sh
cd /path/to/DeepVision3D/EQNet && python setup.py develop
```
(9) Build DVSegmentation.
* Install Google Hashmap:
  ```shell
  conda install -c bioconda google-sparsehash
  ```
* Build DVSegmentation (Please specify the `include_dirs` in [setup.py](../DVSegmentation/ops/setup.py) to your anaconda include path `/home/bing/anaconda3/envs/dv3d/include/`):
  ```shell
  cd /path/to/DeepVision3D/DVSegmentation/ops && python setup.py install
  ```

**Comment by tomztyang** [comment]
So, is the cuda version in your environment cuda11.3?

**Comment by dhliubj** [comment]
> So, is the cuda version in your environment cuda11.3?

Yes. Here is my cuda version.

![Screenshot from 2022-05-20 16-14-25.png](https://s2.loli.net/2022/05/20/xEH7sFm4VeW6fdB.png)

**Comment by tomztyang** [comment]
I think it should be the problem with inconsistent compilation and GPU arch. How about trying adding TORCH_CUDA_ARCH_LIST='8.0+PTX' before `python setup.py xxx`?

**Comment by dhliubj** [comment]
> I think it should be the problem with inconsistent compilation and GPU arch. How about trying adding TORCH_CUDA_ARCH_LIST='8.0+PTX' before `python setup.py xxx`?
------
Thank you very much! @tomztyang 
Using this method has successfully solved my problem. Now I am able to start the train task for DVClassification.

I added `TORCH_CUDA_ARCH_LIST='8.0+PTX'` in the following steps.
  - (6) Build MMDetection3D
  - (7) Build SparseConv library and OpenPCDet (We use spconv v1.2.1).
    - Build spconv library
    - Install OpenPCDet
  - (8) Build EQNet.
  - (9) Build DVSegmentation.

Thanks again for your help.
